export type InternationalStageFormat =
  | "single"
  | "double"
  | "triple"
  | "stepladder"
  | "league"
  | "group"
  | "group_double_elimination"
  | "swiss"
  | "battle_royale";

export type InternationalFormatProfile = {
  id: string;
  game: string;
  gameCode: string;
  title: string;
  years: string;
  teamCount: string;
  qualifierFormats: InternationalStageFormat[];
  finalFormat: InternationalStageFormat;
  summary: string;
  notes: string[];
  sourceLevel: "verified" | "curated" | "generic";
};

export type TeamCountRule = {
  exact?: number[];
  min?: number;
  max?: number;
  label: string;
};

const TEAM_COUNT_RULES: Record<string, TeamCountRule> = {
  "cs-2013-2016": { exact: [16], label: "16팀 고정" },
  "cs-2017": { exact: [16], label: "16팀 고정" },
  "cs-2018-2024": { exact: [24], label: "24팀 고정" },
  "cs-2025-current": { exact: [32], label: "32팀 고정" },
  "lol-2014-2016": { exact: [16], label: "16팀 고정" },
  "lol-2017-2022": { min: 16, max: 24, label: "16-24팀 권장" },
  "lol-2023-current": { min: 16, max: 22, label: "16-22팀 권장" },
  "valo-2021-reykjavik": { exact: [10], label: "10팀 고정" },
  "valo-2022-2023-champions": { exact: [16], label: "16팀 고정" },
  "valo-masters-2024-2026": { exact: [8, 12], label: "8팀 또는 12팀" },
  "valo-kickoff-2026": { min: 8, max: 12, label: "8-12팀 권장" },
  "ow-2018": { exact: [6], label: "6팀 고정" },
  "ow-2019-2025": { min: 8, max: 12, label: "8-12팀 권장" },
  "ow-2026-midseason": { exact: [16], label: "16팀 고정" },
  "dota-ti": { min: 16, max: 20, label: "16-20팀 권장" },
  "dota-ti-2021-2022": { min: 18, max: 20, label: "18-20팀 권장" },
  "dota-ti-2023": { exact: [20], label: "20팀 고정" },
  "dota-ti-2024-current": { exact: [16], label: "16팀 고정" },
  "rlcs-modern": { min: 16, max: 24, label: "16-24팀 권장" },
  "r6-invitational": { min: 16, max: 20, label: "16-20팀 권장" },
  "cod-champs": { min: 8, max: 16, label: "8-16팀 권장" },
  "cod-champs-2019": { exact: [32], label: "32팀 고정" },
  "cod-cdl-2020-2025": { min: 8, max: 12, label: "8-12팀 권장" },
  "halo-championship": { min: 16, max: 24, label: "16-24팀 권장" },
  "moba-groups-knockout": { min: 8, max: 16, label: "8-16팀 권장" },
  "hots-blizzcon-2015-2016": { min: 8, max: 12, label: "8-12팀 권장" },
  "hots-hgc-2017": { exact: [16], label: "16팀 고정" },
  "hots-hgc-2018": { exact: [16], label: "16팀 고정" },
  "hots-post-hgc-community": { min: 8, max: 16, label: "8-16팀 권장" },
  "battle-royale-worlds": { min: 16, max: 40, label: "16-40팀 권장" },
  "apex-championship": { min: 20, max: 40, label: "20-40팀 권장" },
  "apex-algs-2021-2022": { exact: [40], label: "40팀 권장" },
  "apex-algs-2023-2025": { exact: [40], label: "40팀 권장" },
  "pubg-global": { min: 24, max: 32, label: "24-32팀 권장" },
  "pubg-pgc-2019": { exact: [32], label: "32팀 고정" },
  "pubg-pgc-2021": { exact: [32], label: "32팀 고정" },
  "pubg-pgc-2022-2024": { exact: [32], label: "32팀 고정" },
  "pubg-pgc-2025": { min: 24, max: 32, label: "24-32팀 권장" },
  "pubgm-global": { min: 16, max: 48, label: "16-48팀 권장" },
  "fortnite-global": { min: 33, max: 100, label: "33-100팀/듀오 권장" },
  "fortnite-world-cup-2019": { min: 50, max: 100, label: "50-100명/듀오 권장" },
  "fortnite-invitational-2022": { min: 50, max: 100, label: "50-100명/듀오 권장" },
  "fortnite-fncs-2023": { exact: [72], label: "72듀오 권장" },
  "fortnite-fncs-2024-2025": { exact: [33, 50], label: "33트리오 또는 50듀오" },
  "fortnite-fncs-2026": { min: 50, max: 100, label: "50-100듀오 권장" },
  "freefire-global": { min: 12, max: 18, label: "12-18팀 권장" },
  "brawlstars-worlds": { min: 12, max: 16, label: "12-16팀 권장" },
  "wow-arena": { min: 8, max: 12, label: "8-12팀 권장" },
  "starcraft-global": { min: 16, max: 32, label: "16-32명 권장" },
  "tft-worlds": { min: 32, max: 64, label: "32-64명 권장" },
  "fighting-swiss-bracket": { min: 16, max: 512, label: "16명 이상 권장" },
  "fighting-tekken": { min: 16, max: 32, label: "16-32명 권장" },
  "fighting-streetfighter": { min: 16, max: 48, label: "16-48명 권장" },
  "smash-major": { min: 16, max: 1024, label: "16명 이상 권장" },
  "pokemon-worlds": { min: 16, max: 512, label: "16명 이상 권장" },
  "card-strategy-swiss": { min: 8, max: 32, label: "8-32명/팀 권장" },
  "hearthstone-worlds": { min: 8, max: 16, label: "8-16명 권장" },
  "clash-royale-worlds": { min: 8, max: 16, label: "8-16명 권장" },
  "chess-global": { min: 8, max: 206, label: "8-206명 권장" },
  "go-global": { min: 8, max: 64, label: "8-64명 권장" },
  "crossfire-global": { min: 12, max: 16, label: "12-16팀 권장" },
  "eternal-return": { min: 16, max: 40, label: "16-40팀 권장" },
  "football-world-cup-32": { exact: [32], label: "32팀 고정" },
  "football-world-cup-48": { exact: [48], label: "48팀 고정" },
  "uefa-swiss-model": { exact: [36], label: "36팀 고정" }
};

export function getTeamCountRule(profileId: string): TeamCountRule | undefined {
  return TEAM_COUNT_RULES[profileId];
}

export function isTeamCountAllowed(profileId: string, count: number): boolean {
  const rule = getTeamCountRule(profileId);
  if (!rule) return true;
  if (rule.exact) return rule.exact.includes(count);
  if (rule.min !== undefined && count < rule.min) return false;
  if (rule.max !== undefined && count > rule.max) return false;
  return true;
}

export const INTERNATIONAL_FORMAT_PROFILES: InternationalFormatProfile[] = [
  {
    id: "cs-2013-2016",
    game: "Counter-Strike",
    gameCode: "CS",
    title: "Major 2013-2016",
    years: "2013-2016",
    teamCount: "16팀",
    qualifierFormats: ["group_double_elimination"],
    finalFormat: "single",
    summary: "4개 GSL식 조별리그에서 각 조 상위 2팀이 8강 싱글 엘리미네이션으로 진출.",
    notes: ["16팀 -> 4개 조 -> 조별 2팀 진출 -> 8강 본선"],
    sourceLevel: "verified"
  },
  {
    id: "cs-2017",
    game: "Counter-Strike",
    gameCode: "CS",
    title: "Major 2017",
    years: "2017",
    teamCount: "16팀",
    qualifierFormats: ["swiss"],
    finalFormat: "single",
    summary: "16팀 스위스 도입. 3승 진출, 3패 탈락 후 상위 8팀이 본선.",
    notes: ["16팀 스위스 -> 상위 8팀 -> 8강 본선"],
    sourceLevel: "verified"
  },
  {
    id: "cs-2018-2024",
    game: "Counter-Strike",
    gameCode: "CS",
    title: "Major 2018-2024",
    years: "2018-2024",
    teamCount: "24팀",
    qualifierFormats: ["swiss", "swiss"],
    finalFormat: "single",
    summary: "Challengers와 Legends 두 번의 스위스를 거쳐 Champions 8강 싱글 엘리미네이션.",
    notes: ["스위스 2회 -> 8강 토너먼트"],
    sourceLevel: "verified"
  },
  {
    id: "cs-2025-current",
    game: "Counter-Strike",
    gameCode: "CS",
    title: "Major 2025-현재",
    years: "2025-현재",
    teamCount: "32팀",
    qualifierFormats: ["swiss", "swiss", "swiss"],
    finalFormat: "single",
    summary: "Stage 1, Stage 2, Stage 3의 3단계 스위스 후 Playoffs.",
    notes: ["스위스 3회 -> 8강 토너먼트"],
    sourceLevel: "verified"
  },
  {
    id: "lol-2014-2016",
    game: "League of Legends",
    gameCode: "LOL",
    title: "Worlds 2014-2016",
    years: "2014-2016",
    teamCount: "16팀",
    qualifierFormats: ["group"],
    finalFormat: "single",
    summary: "4개 조 조별리그 후 각 조 상위 2팀이 8강 녹아웃으로 진출.",
    notes: ["16팀 -> 4개 조 -> 조별 2팀 -> 8강 Bo5 싱글 엘리미네이션"],
    sourceLevel: "verified"
  },
  {
    id: "lol-2017-2022",
    game: "League of Legends",
    gameCode: "LOL",
    title: "Worlds 2017-2022",
    years: "2017-2022",
    teamCount: "플레이-인 + 16팀 본선",
    qualifierFormats: ["group", "group"],
    finalFormat: "single",
    summary: "플레이-인 후 16팀 그룹 스테이지, 각 조 상위 2팀이 8강.",
    notes: ["플레이-인 -> 그룹 스테이지 -> 8강 녹아웃"],
    sourceLevel: "verified"
  },
  {
    id: "lol-2023-current",
    game: "League of Legends",
    gameCode: "LOL",
    title: "Worlds 2023-현재",
    years: "2023-현재",
    teamCount: "플레이-인 + 16팀 스위스",
    qualifierFormats: ["group_double_elimination", "swiss"],
    finalFormat: "single",
    summary: "플레이-인 이후 16팀 스위스. 3승 진출, 3패 탈락 후 8강 Bo5 녹아웃.",
    notes: ["플레이-인 -> 스위스 -> 8강 녹아웃"],
    sourceLevel: "verified"
  },
  {
    id: "valo-2021-reykjavik",
    game: "VALORANT",
    gameCode: "VALO",
    title: "Masters Reykjavik 2021",
    years: "2021",
    teamCount: "10팀",
    qualifierFormats: [],
    finalFormat: "double",
    summary: "초기 국제대회 실험기. 단독 더블 엘리미네이션 브래킷.",
    notes: ["단독 10팀 더블 엘리미네이션"],
    sourceLevel: "verified"
  },
  {
    id: "valo-2022-2023-champions",
    game: "VALORANT",
    gameCode: "VALO",
    title: "Champions 2022-2023",
    years: "2022-2023",
    teamCount: "16팀",
    qualifierFormats: ["group_double_elimination"],
    finalFormat: "double",
    summary: "4개 GSL 조별리그 후 8팀 더블 엘리미네이션 플레이오프.",
    notes: ["GSL 조별 -> 8팀 더블 엘리미네이션"],
    sourceLevel: "verified"
  },
  {
    id: "valo-masters-2024-2026",
    game: "VALORANT",
    gameCode: "VALO",
    title: "Masters 2024-2026",
    years: "2024-2026",
    teamCount: "8-12팀",
    qualifierFormats: ["swiss"],
    finalFormat: "double",
    summary: "스위스 통과 팀과 직행 시드가 합류해 더블 엘리미네이션 플레이오프.",
    notes: ["스위스 -> 4팀 또는 8팀 더블 엘리미네이션"],
    sourceLevel: "verified"
  },
  {
    id: "valo-kickoff-2026",
    game: "VALORANT",
    gameCode: "VALO",
    title: "Kickoff 2026",
    years: "2026",
    teamCount: "지역별",
    qualifierFormats: [],
    finalFormat: "triple",
    summary: "세 번 패배하면 탈락하는 트리플 엘리미네이션 계열.",
    notes: ["단독 트리플 엘리미네이션"],
    sourceLevel: "verified"
  },
  {
    id: "ow-2018",
    game: "Overwatch",
    gameCode: "OW",
    title: "OWL Playoffs 2018",
    years: "2018",
    teamCount: "6팀",
    qualifierFormats: [],
    finalFormat: "single",
    summary: "상위 1, 2시드가 부전승을 받고 3-6시드가 먼저 경기하는 6팀 플레이오프.",
    notes: ["6팀 싱글 엘리미네이션 + 상위 시드 부전승"],
    sourceLevel: "verified"
  },
  {
    id: "ow-2019-2025",
    game: "Overwatch",
    gameCode: "OW",
    title: "OWL/OWCS 2019-2025",
    years: "2019-2025",
    teamCount: "8-12팀",
    qualifierFormats: [],
    finalFormat: "double",
    summary: "승자조와 패자조가 있는 더블 엘리미네이션 중심 플레이오프.",
    notes: ["8팀 또는 12팀 더블 엘리미네이션"],
    sourceLevel: "verified"
  },
  {
    id: "ow-2026-midseason",
    game: "Overwatch",
    gameCode: "OW",
    title: "OWCS 2026 Midseason 계열",
    years: "2026",
    teamCount: "16팀",
    qualifierFormats: ["group_double_elimination"],
    finalFormat: "single",
    summary: "2개 8팀 더블 엘리미네이션 그룹 후 싱글 엘리미네이션 플레이오프.",
    notes: ["더블엘리 그룹 -> 싱글 엘리미네이션"],
    sourceLevel: "verified"
  },
  {
    id: "dota-ti",
    game: "Dota 2",
    gameCode: "DOTA",
    title: "The International 계열",
    years: "대표 국제대회",
    teamCount: "16-20팀",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "조별/그룹 단계를 거친 뒤 메인 이벤트는 더블 엘리미네이션 계열.",
    notes: ["그룹 -> 더블 엘리미네이션"],
    sourceLevel: "curated"
  },
  {
    id: "dota-ti-2021-2022",
    game: "Dota 2",
    gameCode: "DOTA",
    title: "The International 2021-2022",
    years: "2021-2022",
    teamCount: "18-20팀",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "라운드 로빈 그룹으로 상위조/하위조 시드를 나누고 메인 이벤트는 더블 엘리미네이션.",
    notes: ["그룹 라운드 로빈 -> 상위조/하위조 더블 엘리미네이션"],
    sourceLevel: "verified"
  },
  {
    id: "dota-ti-2023",
    game: "Dota 2",
    gameCode: "DOTA",
    title: "The International 2023",
    years: "2023",
    teamCount: "20팀",
    qualifierFormats: ["group", "group_double_elimination"],
    finalFormat: "double",
    summary: "4개 조 싱글 라운드 로빈 후 Phase 2 매치로 상위조/하위조 배정, 이후 더블 엘리미네이션.",
    notes: ["그룹 Phase 1 -> 배정 매치 Phase 2 -> 더블 엘리미네이션"],
    sourceLevel: "verified"
  },
  {
    id: "dota-ti-2024-current",
    game: "Dota 2",
    gameCode: "DOTA",
    title: "The International 2024-현재",
    years: "2024-현재",
    teamCount: "16팀",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "16팀 그룹 스테이지 후 더블 엘리미네이션 플레이오프.",
    notes: ["그룹 -> 더블 엘리미네이션"],
    sourceLevel: "verified"
  },
  {
    id: "rlcs-modern",
    game: "Rocket League",
    gameCode: "RL",
    title: "RLCS 현대 포맷 계열",
    years: "대표 국제대회",
    teamCount: "16팀 내외",
    qualifierFormats: ["swiss"],
    finalFormat: "single",
    summary: "스위스 또는 그룹 단계 후 싱글 엘리미네이션 플레이오프.",
    notes: ["스위스 -> 싱글 엘리미네이션"],
    sourceLevel: "curated"
  },
  {
    id: "r6-invitational",
    game: "Rainbow Six Siege",
    gameCode: "R6",
    title: "Six Invitational 계열",
    years: "대표 국제대회",
    teamCount: "20팀 내외",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "그룹 스테이지 후 더블 엘리미네이션 플레이오프를 쓰는 계열.",
    notes: ["그룹 -> 더블 엘리미네이션"],
    sourceLevel: "curated"
  },
  {
    id: "cod-champs",
    game: "Call of Duty",
    gameCode: "COD",
    title: "Champs 계열",
    years: "대표 국제대회",
    teamCount: "8-16팀",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "풀/그룹 플레이 후 더블 엘리미네이션 챔피언십 브래킷.",
    notes: ["그룹 -> 더블 엘리미네이션"],
    sourceLevel: "curated"
  },
  {
    id: "cod-champs-2019",
    game: "Call of Duty",
    gameCode: "COD",
    title: "CWL Championship 2019",
    years: "2019",
    teamCount: "32팀",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "4팀 풀 플레이로 브래킷 시드를 정하고 더블 엘리미네이션 챔피언십 브래킷 진행.",
    notes: ["풀 플레이 -> 더블 엘리미네이션"],
    sourceLevel: "verified"
  },
  {
    id: "cod-cdl-2020-2025",
    game: "Call of Duty",
    gameCode: "COD",
    title: "CDL Championship 2020-2025",
    years: "2020-2025",
    teamCount: "8-12팀",
    qualifierFormats: [],
    finalFormat: "double",
    summary: "프랜차이즈 CDL 포인트/시드 기반 최종 플레이오프. 본선은 더블 엘리미네이션 중심.",
    notes: ["시드 배정 -> 더블 엘리미네이션"],
    sourceLevel: "curated"
  },
  {
    id: "halo-championship",
    game: "Halo",
    gameCode: "HALO",
    title: "World Championship 계열",
    years: "대표 국제대회",
    teamCount: "16팀 내외",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "풀 플레이 후 챔피언십 더블 엘리미네이션 브래킷.",
    notes: ["그룹 -> 더블 엘리미네이션"],
    sourceLevel: "curated"
  },
  {
    id: "moba-groups-knockout",
    game: "MOBA 국제대회 공통",
    gameCode: "HOK/MBLL/MR/HOTS",
    title: "그룹 + 녹아웃 계열",
    years: "대표 국제대회",
    teamCount: "8-16팀",
    qualifierFormats: ["group"],
    finalFormat: "single",
    summary: "조별리그 또는 그룹 스테이지 후 싱글 엘리미네이션 본선.",
    notes: ["그룹 -> 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "hots-blizzcon-2015-2016",
    game: "Heroes of the Storm",
    gameCode: "HOTS",
    title: "World Championship 2015-2016",
    years: "2015-2016",
    teamCount: "8-12팀",
    qualifierFormats: ["group"],
    finalFormat: "single",
    summary: "초기 글로벌 챔피언십 계열. 조별리그로 상위 팀을 추리고 싱글 엘리미네이션 결선 진행.",
    notes: ["그룹 -> 싱글 엘리미네이션"],
    sourceLevel: "curated"
  },
  {
    id: "hots-hgc-2017",
    game: "Heroes of the Storm",
    gameCode: "HOTS",
    title: "HGC Finals 2017",
    years: "2017",
    teamCount: "16팀",
    qualifierFormats: ["group"],
    finalFormat: "single",
    summary: "HGC 체제의 글로벌 파이널. 그룹 스테이지 후 플레이오프 브래킷으로 우승 결정.",
    notes: ["그룹 -> 싱글 엘리미네이션"],
    sourceLevel: "curated"
  },
  {
    id: "hots-hgc-2018",
    game: "Heroes of the Storm",
    gameCode: "HOTS",
    title: "HGC Finals 2018",
    years: "2018",
    teamCount: "16팀",
    qualifierFormats: ["group"],
    finalFormat: "single",
    summary: "HGC 마지막 글로벌 파이널 계열. 조별 단계 후 싱글 엘리미네이션 플레이오프.",
    notes: ["그룹 -> 싱글 엘리미네이션"],
    sourceLevel: "curated"
  },
  {
    id: "hots-post-hgc-community",
    game: "Heroes of the Storm",
    gameCode: "HOTS",
    title: "Post-HGC 커뮤니티 국제대회",
    years: "2019-현재",
    teamCount: "대회별",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "공식 HGC 종료 이후 커뮤니티/초청전 성격이 강해져 그룹 후 더블 엘리 또는 싱글 결선으로 구성하기 적합.",
    notes: ["그룹 -> 더블 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "battle-royale-worlds",
    game: "Battle Royale",
    gameCode: "PUBG/PUBGM/APEX/FN/FF/BS",
    title: "누적 리더보드 계열",
    years: "대표 국제대회",
    teamCount: "16-40팀",
    qualifierFormats: ["battle_royale"],
    finalFormat: "battle_royale",
    summary: "여러 라운드 기록으로 예선과 결승 리더보드를 나누는 방식.",
    notes: ["배틀로얄 예선 -> 배틀로얄 결승"],
    sourceLevel: "generic"
  },
  {
    id: "fighting-swiss-bracket",
    game: "Fighting / 1v1",
    gameCode: "TK/SF/SMB/PKMN",
    title: "스위스 + 컷오프 브래킷 계열",
    years: "대표 국제대회",
    teamCount: "참가자 규모별",
    qualifierFormats: ["swiss"],
    finalFormat: "single",
    summary: "대규모 참가자 풀을 스위스로 줄이고 상위 컷오프를 싱글 브래킷으로 진행.",
    notes: ["스위스 -> 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "card-strategy-swiss",
    game: "Card / Strategy",
    gameCode: "HS/SC/TFT/GO/CH/CR/CF",
    title: "스위스 또는 라운드 로빈 + 플레이오프",
    years: "대표 국제대회",
    teamCount: "8-32명/팀",
    qualifierFormats: ["swiss"],
    finalFormat: "single",
    summary: "스위스/리그식 예선 후 상위권이 플레이오프 브래킷으로 진출.",
    notes: ["스위스 -> 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "apex-championship",
    game: "Apex Legends",
    gameCode: "APEX",
    title: "ALGS Championship 계열",
    years: "대표 국제대회",
    teamCount: "40팀 내외",
    qualifierFormats: ["battle_royale", "battle_royale"],
    finalFormat: "battle_royale",
    summary: "그룹/브래킷 스테이지를 라운드 기록으로 진행하고 결승도 배틀로얄 리더보드로 운영.",
    notes: ["배틀로얄 예선 -> 배틀로얄 준결승 -> 배틀로얄 결승"],
    sourceLevel: "generic"
  },
  {
    id: "apex-algs-2021-2022",
    game: "Apex Legends",
    gameCode: "APEX",
    title: "ALGS Championship 2021-2022",
    years: "2021-2022",
    teamCount: "40팀 내외",
    qualifierFormats: ["battle_royale", "battle_royale"],
    finalFormat: "battle_royale",
    summary: "그룹 스테이지와 브래킷/세미 파이널을 점수 누적으로 치른 뒤 매치 포인트 결승.",
    notes: ["그룹 리더보드 -> 브래킷/세미 리더보드 -> 결승"],
    sourceLevel: "curated"
  },
  {
    id: "apex-algs-2023-2025",
    game: "Apex Legends",
    gameCode: "APEX",
    title: "ALGS Championship 2023-2025",
    years: "2023-2025",
    teamCount: "40팀",
    qualifierFormats: ["battle_royale", "battle_royale", "battle_royale"],
    finalFormat: "battle_royale",
    summary: "그룹 스테이지, 승자/패자 브래킷형 리더보드, 결승 로비로 이어지는 다단계 배틀로얄.",
    notes: ["그룹 -> 승자/패자 리더보드 -> 라스트 찬스 -> 결승"],
    sourceLevel: "curated"
  },
  {
    id: "pubg-global",
    game: "PUBG",
    gameCode: "PUBG",
    title: "PGC/PGS 계열",
    years: "대표 국제대회",
    teamCount: "24-32팀",
    qualifierFormats: ["battle_royale"],
    finalFormat: "battle_royale",
    summary: "라운드별 순위와 킬 점수 누적으로 예선과 결승 리더보드를 구성.",
    notes: ["누적 리더보드 -> 결승 리더보드"],
    sourceLevel: "generic"
  },
  {
    id: "pubg-pgc-2019",
    game: "PUBG",
    gameCode: "PUBG",
    title: "PGC 2019",
    years: "2019",
    teamCount: "32팀",
    qualifierFormats: ["battle_royale", "battle_royale"],
    finalFormat: "battle_royale",
    summary: "그룹 스테이지와 세미 파이널을 라운드 기록으로 거쳐 그랜드 파이널 리더보드로 우승 결정.",
    notes: ["그룹 -> 세미 파이널 -> 그랜드 파이널"],
    sourceLevel: "curated"
  },
  {
    id: "pubg-pgc-2021",
    game: "PUBG",
    gameCode: "PUBG",
    title: "PGC 2021",
    years: "2021",
    teamCount: "32팀",
    qualifierFormats: ["battle_royale", "battle_royale", "battle_royale"],
    finalFormat: "battle_royale",
    summary: "Rank Decision, Weekly Survival/Finals, Grand Survival을 거쳐 Grand Finals로 이어진 독특한 생존형 포맷.",
    notes: ["순위 결정 -> 주간 생존/결승 -> 그랜드 서바이벌 -> 결승"],
    sourceLevel: "curated"
  },
  {
    id: "pubg-pgc-2022-2024",
    game: "PUBG",
    gameCode: "PUBG",
    title: "PGC 2022-2024",
    years: "2022-2024",
    teamCount: "32팀",
    qualifierFormats: ["battle_royale", "battle_royale", "battle_royale"],
    finalFormat: "battle_royale",
    summary: "그룹 스테이지 후 승자/패자 브래킷형 누적 리더보드와 그랜드 파이널로 이어지는 현대 PGC 계열.",
    notes: ["그룹 -> 승자/패자 브래킷 -> 그랜드 파이널"],
    sourceLevel: "curated"
  },
  {
    id: "pubg-pgc-2025",
    game: "PUBG",
    gameCode: "PUBG",
    title: "PGC 2025 계열",
    years: "2025",
    teamCount: "대회별",
    qualifierFormats: ["battle_royale", "battle_royale", "battle_royale"],
    finalFormat: "battle_royale",
    summary: "최근 PUBG 글로벌 대회 흐름에 맞춘 그룹/브래킷/라스트 찬스/결승 리더보드 템플릿.",
    notes: ["그룹 -> 브래킷 -> 라스트 찬스 -> 결승"],
    sourceLevel: "curated"
  },
  {
    id: "pubgm-global",
    game: "PUBG Mobile",
    gameCode: "PUBGM",
    title: "PMGC 계열",
    years: "대표 국제대회",
    teamCount: "16-48팀",
    qualifierFormats: ["battle_royale", "battle_royale"],
    finalFormat: "battle_royale",
    summary: "그룹/서바이벌/라스트 찬스 같은 라운드 기록 단계를 거쳐 결승 리더보드로 연결.",
    notes: ["배틀로얄 다단계 -> 결승 리더보드"],
    sourceLevel: "generic"
  },
  {
    id: "fortnite-global",
    game: "Fortnite",
    gameCode: "FN",
    title: "FNCS Global 계열",
    years: "대표 국제대회",
    teamCount: "듀오/스쿼드 규모별",
    qualifierFormats: ["battle_royale"],
    finalFormat: "battle_royale",
    summary: "여러 매치 기록으로 최종 순위를 결정하는 배틀로얄 결승형.",
    notes: ["라운드 기록 -> 최종 리더보드"],
    sourceLevel: "generic"
  },
  {
    id: "fortnite-world-cup-2019",
    game: "Fortnite",
    gameCode: "FN",
    title: "World Cup 2019",
    years: "2019",
    teamCount: "솔로/듀오",
    qualifierFormats: [],
    finalFormat: "battle_royale",
    summary: "온라인 예선 통과자들이 월드컵 결승에서 여러 매치 기록으로 우승자를 결정.",
    notes: ["단독 결승 리더보드"],
    sourceLevel: "curated"
  },
  {
    id: "fortnite-invitational-2022",
    game: "Fortnite",
    gameCode: "FN",
    title: "FNCS Invitational 2022",
    years: "2022",
    teamCount: "듀오",
    qualifierFormats: [],
    finalFormat: "battle_royale",
    summary: "초청 LAN 결승형. 여러 매치 기록으로 최종 순위 결정.",
    notes: ["단독 결승 리더보드"],
    sourceLevel: "curated"
  },
  {
    id: "fortnite-fncs-2023",
    game: "Fortnite",
    gameCode: "FN",
    title: "FNCS Global Championship 2023",
    years: "2023",
    teamCount: "72듀오",
    qualifierFormats: ["battle_royale", "battle_royale"],
    finalFormat: "battle_royale",
    summary: "Upper Bracket 상위권은 결승 직행, 나머지는 Lower Bracket으로 남은 결승 슬롯 경쟁.",
    notes: ["상위 브래킷 -> 하위 브래킷 -> 그랜드 파이널"],
    sourceLevel: "verified"
  },
  {
    id: "fortnite-fncs-2024-2025",
    game: "Fortnite",
    gameCode: "FN",
    title: "FNCS Global Championship 2024-2025",
    years: "2024-2025",
    teamCount: "50듀오 / 33트리오",
    qualifierFormats: [],
    finalFormat: "battle_royale",
    summary: "글로벌 결승 리더보드 중심. 2024는 듀오, 2025는 트리오 라운드 기록 결승.",
    notes: ["결승 리더보드"],
    sourceLevel: "verified"
  },
  {
    id: "fortnite-fncs-2026",
    game: "Fortnite",
    gameCode: "FN",
    title: "FNCS Global Championship 2026",
    years: "2026",
    teamCount: "듀오 예정",
    qualifierFormats: ["battle_royale"],
    finalFormat: "battle_royale",
    summary: "2026은 듀오 복귀 예정. Major/Summit 계열 선발 후 글로벌 결승으로 연결.",
    notes: ["시즌 선발 -> 결승 리더보드"],
    sourceLevel: "curated"
  },
  {
    id: "freefire-global",
    game: "Free Fire",
    gameCode: "FF",
    title: "World Series 계열",
    years: "대표 국제대회",
    teamCount: "12-18팀",
    qualifierFormats: ["battle_royale"],
    finalFormat: "battle_royale",
    summary: "포인트 러시/결승 등 라운드 기록 기반 스테이지를 쓰는 계열.",
    notes: ["배틀로얄 예선 -> 결승 리더보드"],
    sourceLevel: "generic"
  },
  {
    id: "brawlstars-worlds",
    game: "Brawl Stars",
    gameCode: "BS",
    title: "World Finals 계열",
    years: "대표 국제대회",
    teamCount: "12-16팀",
    qualifierFormats: ["group"],
    finalFormat: "single",
    summary: "그룹 스테이지로 상위 팀을 추린 뒤 싱글 엘리미네이션 플레이오프로 진행.",
    notes: ["그룹 -> 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "wow-arena",
    game: "World of Warcraft",
    gameCode: "WOW",
    title: "AWC 계열",
    years: "대표 국제대회",
    teamCount: "8팀 내외",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "그룹 또는 라운드 로빈 후 상위 팀이 더블 엘리미네이션 브래킷으로 진출.",
    notes: ["그룹/리그 -> 더블 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "starcraft-global",
    game: "StarCraft",
    gameCode: "SC",
    title: "글로벌 챔피언십 계열",
    years: "대표 국제대회",
    teamCount: "16-32명",
    qualifierFormats: ["group_double_elimination"],
    finalFormat: "single",
    summary: "GSL식 조별리그 또는 듀얼 토너먼트 후 싱글 엘리미네이션 본선.",
    notes: ["GSL 조별 -> 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "tft-worlds",
    game: "Teamfight Tactics",
    gameCode: "TFT",
    title: "Tactician's Crown 계열",
    years: "대표 국제대회",
    teamCount: "32명 내외",
    qualifierFormats: ["battle_royale", "battle_royale"],
    finalFormat: "battle_royale",
    summary: "로비별 순위 점수를 누적해 컷오프를 반복하고 최종 로비에서 우승자를 결정.",
    notes: ["로비 점수 누적 -> 컷오프 -> 결승 로비"],
    sourceLevel: "generic"
  },
  {
    id: "fighting-tekken",
    game: "Tekken",
    gameCode: "TK",
    title: "World Tour Finals 계열",
    years: "대표 국제대회",
    teamCount: "16-32명",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "그룹/풀 플레이 후 격투게임식 더블 엘리미네이션 결선으로 진행.",
    notes: ["그룹 -> 더블 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "fighting-streetfighter",
    game: "Street Fighter",
    gameCode: "SF",
    title: "Capcom Cup 계열",
    years: "대표 국제대회",
    teamCount: "16-48명",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "조별/풀 스테이지 후 더블 엘리미네이션 또는 컷오프 브래킷.",
    notes: ["그룹 -> 더블 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "smash-major",
    game: "Smash",
    gameCode: "SMB",
    title: "Major 계열",
    years: "대표 국제대회",
    teamCount: "참가자 규모별",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "풀/브래킷 풀 이후 더블 엘리미네이션 결선으로 좁히는 계열.",
    notes: ["풀 -> 더블 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "pokemon-worlds",
    game: "Pokemon",
    gameCode: "PKMN",
    title: "World Championships 계열",
    years: "대표 국제대회",
    teamCount: "부문별",
    qualifierFormats: ["swiss"],
    finalFormat: "single",
    summary: "스위스 라운드 후 상위 컷오프 싱글 엘리미네이션.",
    notes: ["스위스 -> 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "hearthstone-worlds",
    game: "Hearthstone",
    gameCode: "HS",
    title: "World Championship 계열",
    years: "대표 국제대회",
    teamCount: "8-16명",
    qualifierFormats: ["group"],
    finalFormat: "single",
    summary: "그룹 스테이지 후 상위 플레이어가 싱글 엘리미네이션 결선으로 진출.",
    notes: ["그룹 -> 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "clash-royale-worlds",
    game: "Clash Royale",
    gameCode: "CR",
    title: "World Finals 계열",
    years: "대표 국제대회",
    teamCount: "8-16명",
    qualifierFormats: ["swiss"],
    finalFormat: "single",
    summary: "스위스 또는 그룹식 예선 후 싱글 엘리미네이션 결선.",
    notes: ["스위스 -> 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "chess-global",
    game: "Chess",
    gameCode: "CH",
    title: "월드컵/체스닷컴 계열",
    years: "대표 국제대회",
    teamCount: "8-206명",
    qualifierFormats: [],
    finalFormat: "single",
    summary: "대형 토너먼트는 싱글 엘리미네이션 매치 브래킷으로 운영되는 경우가 많음.",
    notes: ["단독 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "go-global",
    game: "Go",
    gameCode: "GO",
    title: "세계기전 계열",
    years: "대표 국제대회",
    teamCount: "대회별",
    qualifierFormats: [],
    finalFormat: "single",
    summary: "본선 토너먼트형 싱글 엘리미네이션 또는 단계별 매치 브래킷.",
    notes: ["단독 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "crossfire-global",
    game: "CrossFire",
    gameCode: "CF",
    title: "CFS 계열",
    years: "대표 국제대회",
    teamCount: "12-16팀",
    qualifierFormats: ["group"],
    finalFormat: "single",
    summary: "그룹 스테이지 후 녹아웃 플레이오프.",
    notes: ["그룹 -> 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "eternal-return",
    game: "Eternal Return",
    gameCode: "ER",
    title: "Masters/Finals 계열",
    years: "대표 국제대회",
    teamCount: "로비 규모별",
    qualifierFormats: ["battle_royale"],
    finalFormat: "battle_royale",
    summary: "라운드별 순위 점수 누적으로 결승 진출과 우승자를 가르는 방식.",
    notes: ["라운드 기록 -> 결승 리더보드"],
    sourceLevel: "generic"
  },
  {
    id: "realm-shooter-generic",
    game: "RS",
    gameCode: "RS",
    title: "슈터 국제대회 계열",
    years: "대표 국제대회",
    teamCount: "8-16팀",
    qualifierFormats: ["group"],
    finalFormat: "double",
    summary: "그룹 스테이지 후 더블 엘리미네이션 플레이오프를 쓰는 슈터 계열 템플릿.",
    notes: ["그룹 -> 더블 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "deadbydaylight-generic",
    game: "Dead by Daylight",
    gameCode: "DBD",
    title: "커뮤니티 월드컵 계열",
    years: "대표 국제대회",
    teamCount: "8-16팀",
    qualifierFormats: ["group"],
    finalFormat: "single",
    summary: "그룹/리그식 예선 후 싱글 엘리미네이션 결선으로 연결하기 적합한 템플릿.",
    notes: ["그룹 -> 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "kart-racer-generic",
    game: "Kart Racer",
    gameCode: "KR",
    title: "레이싱 리그 결선 계열",
    years: "대표 국제대회",
    teamCount: "8-16팀",
    qualifierFormats: ["league"],
    finalFormat: "stepladder",
    summary: "순위표 기반 리그 후 상위 시드가 유리한 스텝래더 결선.",
    notes: ["리그 -> 스텝래더"],
    sourceLevel: "generic"
  },
  {
    id: "ftl-fury-generic",
    game: "FTLFRY",
    gameCode: "FTLFRY",
    title: "액션/아레나 컵 계열",
    years: "대표 국제대회",
    teamCount: "8-16팀",
    qualifierFormats: ["swiss"],
    finalFormat: "double",
    summary: "스위스 예선 후 더블 엘리미네이션 결선으로 안정적으로 구성 가능한 템플릿.",
    notes: ["스위스 -> 더블 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "byeolsae-generic",
    game: "Byeolsae",
    gameCode: "Byeolsae",
    title: "커스텀 컵 계열",
    years: "대표 국제대회",
    teamCount: "대회별",
    qualifierFormats: ["league"],
    finalFormat: "single",
    summary: "리그 예선 후 상위 팀이 녹아웃으로 진출하는 범용 템플릿.",
    notes: ["리그 -> 싱글 엘리미네이션"],
    sourceLevel: "generic"
  },
  {
    id: "football-world-cup-32",
    game: "Football",
    gameCode: "FC",
    title: "월드컵 32팀 계열",
    years: "1998-2022",
    teamCount: "32팀",
    qualifierFormats: ["group"],
    finalFormat: "single",
    summary: "8개 조 조별리그 후 16강 싱글 엘리미네이션.",
    notes: ["그룹 -> 16강 녹아웃"],
    sourceLevel: "curated"
  },
  {
    id: "football-world-cup-48",
    game: "Football",
    gameCode: "FC",
    title: "월드컵 48팀 계열",
    years: "2026-",
    teamCount: "48팀",
    qualifierFormats: ["group"],
    finalFormat: "single",
    summary: "12개 조 이후 32강 녹아웃으로 이어지는 대형 본선.",
    notes: ["그룹 -> 32강 녹아웃"],
    sourceLevel: "curated"
  },
  {
    id: "uefa-swiss-model",
    game: "Football",
    gameCode: "FC",
    title: "UEFA Swiss Model 계열",
    years: "2024-2027",
    teamCount: "36팀",
    qualifierFormats: ["league"],
    finalFormat: "single",
    summary: "단일 리그 테이블 후 플레이오프/녹아웃으로 진출하는 스위스 모델 계열.",
    notes: ["리그 테이블 -> 녹아웃"],
    sourceLevel: "curated"
  }
];

export function getInternationalFormatProfile(id: string) {
  return INTERNATIONAL_FORMAT_PROFILES.find((profile) => profile.id === id);
}

export function getInternationalFormatGroups() {
  return INTERNATIONAL_FORMAT_PROFILES.reduce<Record<string, InternationalFormatProfile[]>>((groups, profile) => {
    const key = `${profile.game} (${profile.gameCode})`;
    groups[key] = [...(groups[key] ?? []), profile];
    return groups;
  }, {});
}
